### ISSUE TITLE
Navegación dentro de página con scroll animado

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/project-promo-j-module-1-team-3#2]
Buenos días criaturas, tengo una duda para preguntaros y he pensado que este puede ser un buen sitio.

Al pulsar en los botones del menú de vuestra página, la página hace scroll hasta la sección clickada con una animación. 

Mi pregunta es: ¿La animación la habéis puesto vosotras con algún código de JS?

Gracias

**Comment by BbeatrizSI** [comment]
Hola Miguel,
Que va... Tenemos los enlaces de la manera normal (<a href="#who">QUIÉNES SOMOS</a> en HTML y nada más en CSS) no sé a qué se debe la animación. ¿A las demás no les pasa? No me he fijado...

**Comment by sandra1894** [comment]
Buenas Miguel, 
No entiendo la animación que dices que hace, si quieres mañana nos lo cuentas en la hora de proyecto, o si mis compis saben a que te refieres que me lo digan ellas :)

**Comment by elevalgue** [comment]
Hola!
Es cierto, no hemos añadido ninguna animación :s

**Comment by migueldelmazo** [comment]
Pues debe ser una nueva funcionalidad de Chrome, que me gusta mucho. Gracias por info chicas. Cierro este issue.
